name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      
      - name: Install SoftHSM 2
        env:
          PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
        run: |
            sudo apt update
            sudo apt install -f libsofthsm2 -y
            sudo usermod -a -G softhsm $USER
            softhsm --init-token --slot 0 --label test --pin 1234

      - name: build
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: rm -fr zig-cache && zig fmt --check --ast-check */*.zig