name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      
      - name: Install SoftHSM 2
        run: |
            sudo apt update
            sudo apt install softhsm2 -y

      - name: build
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: rm -fr zig-cache && zig fmt --check --ast-check */*.zig