name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.10.0
      
      - name: Install SoftHSM 2
        env:
          PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
          SOFTHSM2_CONF: /etc/softhsm/softhsm2.conf
        run: |
            sudo apt update
            sudo apt install -f libsofthsm2 -y
            sudo usermod -a -G softhsm $USER
            mkdir -p $HOME/lib/softhsm/tokens && echo "directories.tokendir = $HOME/lib/softhsm/tokens" > $HOME/lib/softhsm/softhsm2.conf
            sudo chown -R $USER:$USER $HOME/lib/softhsm
            export SOFTHSM2_CONF=$HOME/lib/softhsm/softhsm2.conf
            sudo cp rbuild_lib/libsofthsm2.* /usr/lib/softhsm
            softhsm2-util --init-token --slot 0 --label "Test" --so-pin "1122334455" --pin "1122334455" --serial `shuf -i 0-9999 -n1`

      - name: build
        run: |
            echo -e "Stage 3 test" && zig build test
            rm -rf zig-cache
            echo -e "Stage 1 test" && zig build test -fstage1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: |
            rm -rf zig-cache
            zig fmt --check --ast-check **.zig
